package repository

import (
	"testing"

	"github.com/ramith/service-now-mapping-service/internal/models"
	"github.com/stretchr/testify/assert"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

































































































































































}	assert.Error(t, err)	_, err = repo.GetBySysID("test-sys-id-delete")	// Verify deletion (should not be found)		assert.NoError(t, err)	err = repo.Delete(mapping.ID)	// Delete the mapping		assert.NoError(t, err)	err := repo.Create(mapping)	}		APIVersion: "v1.0.0",		APIName:    "Delete API",		APIID:      "api-delete",		SysID:      "test-sys-id-delete",	mapping := &models.APIMapping{	// Create test data		repo := NewAPIMappingRepository(db)	db := setupTestDB(t)func TestDelete(t *testing.T) {}	assert.Equal(t, "v2.0.0", result.APIVersion)	assert.Equal(t, "Updated API", result.APIName)	assert.NoError(t, err)	result, err := repo.GetBySysID("test-sys-id-update")	// Verify update		assert.NoError(t, err)	err = repo.Update(mapping)	mapping.APIVersion = "v2.0.0"	mapping.APIName = "Updated API"	// Update the mapping		assert.NoError(t, err)	err := repo.Create(mapping)	}		APIVersion: "v1.0.0",		APIName:    "Original API",		APIID:      "api-update",		SysID:      "test-sys-id-update",	mapping := &models.APIMapping{	// Create test data		repo := NewAPIMappingRepository(db)	db := setupTestDB(t)func TestUpdate(t *testing.T) {}	assert.Len(t, results, 3)	assert.NoError(t, err)	results, err := repo.GetAll()	// Test retrieval		}		assert.NoError(t, err)		err := repo.Create(&mappings[i])	for i := range mappings {		}		{SysID: "sys-3", APIID: "api-3", APIName: "API 3", APIVersion: "v3"},		{SysID: "sys-2", APIID: "api-2", APIName: "API 2", APIVersion: "v2"},		{SysID: "sys-1", APIID: "api-1", APIName: "API 1", APIVersion: "v1"},	mappings := []models.APIMapping{	// Create multiple test records		repo := NewAPIMappingRepository(db)	db := setupTestDB(t)func TestGetAll(t *testing.T) {}	assert.Equal(t, "v1.5.0", result.APIVersion)	assert.Equal(t, "User Management API", result.APIName)	assert.NoError(t, err)	result, err := repo.GetByNameAndVersion("User Management API", "v1.5.0")	// Test retrieval		assert.NoError(t, err)	err := repo.Create(mapping)	}		APIVersion: "v1.5.0",		APIName:    "User Management API",		APIID:      "api-004",		SysID:      "test-sys-id-101",	mapping := &models.APIMapping{	// Create test data		repo := NewAPIMappingRepository(db)	db := setupTestDB(t)func TestGetByNameAndVersion(t *testing.T) {}	assert.Equal(t, "Test API 3", result.APIName)	assert.Equal(t, "api-003", result.APIID)	assert.NoError(t, err)	result, err := repo.GetByAPIID("api-003")	// Test retrieval		assert.NoError(t, err)	err := repo.Create(mapping)	}		APIVersion: "v3.0.0",		APIName:    "Test API 3",		APIID:      "api-003",		SysID:      "test-sys-id-789",	mapping := &models.APIMapping{	// Create test data		repo := NewAPIMappingRepository(db)	db := setupTestDB(t)func TestGetByAPIID(t *testing.T) {}	assert.Equal(t, "api-002", result.APIID)	assert.Equal(t, "test-sys-id-456", result.SysID)	assert.NoError(t, err)	result, err := repo.GetBySysID("test-sys-id-456")	// Test retrieval		assert.NoError(t, err)	err := repo.Create(mapping)	}		APIVersion: "v2.0.0",		APIName:    "Test API 2",		APIID:      "api-002",		SysID:      "test-sys-id-456",	mapping := &models.APIMapping{	// Create test data		repo := NewAPIMappingRepository(db)	db := setupTestDB(t)func TestGetBySysID(t *testing.T) {}	assert.NotZero(t, mapping.ID)	assert.NoError(t, err)	err := repo.Create(mapping)		}		APIVersion: "v1.0.0",		APIName:    "Test API",		APIID:      "api-001",		SysID:      "test-sys-id-123",	mapping := &models.APIMapping{		repo := NewAPIMappingRepository(db)	db := setupTestDB(t)func TestCreate(t *testing.T) {}	return db		assert.NoError(t, err)	err = db.AutoMigrate(&models.APIMapping{})		assert.NoError(t, err)	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})func setupTestDB(t *testing.T) *gorm.DB {